# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

Exception: ignored

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
a.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:



null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
a = np.array([1,2,3,4,5])
reverse = a[::-1]
reverse

array([5, 4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
a= np.arange(0,9)
re= a.reshape(3,3)
re

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
a = [1,2,0,0,4,0]
for i,v in enumerate(a):
  if v!=0:
    print(i)

0
1
4


In [22]:
a=np.array([1,2,0,0,4,0])
b=np.nonzero(a)
b

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:


# Create a 3x3 identity matrix using identity function
identity_matrix = np.identity(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
a = np.random.rand(3,3,3)
a



array([[[0.06218259, 0.89107517, 0.49573225],
        [0.93560741, 0.41688951, 0.08011591],
        [0.75729473, 0.92529477, 0.90642935]],

       [[0.01290653, 0.4456021 , 0.20984299],
        [0.22693784, 0.05538658, 0.44016884],
        [0.81660983, 0.99218895, 0.45136187]],

       [[0.32184792, 0.51691538, 0.06550312],
        [0.55269865, 0.98334739, 0.04645608],
        [0.62109452, 0.93968052, 0.32512429]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
a= np.random.rand(10,10)
a
np.max(a)
np.min(a)

0.03629222692549883

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
a= np.random.rand(30)
np.mean(a)

0.4671818034331341

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
# Create a 2D array filled with zeros
array_2d = np.zeros((5, 5), dtype=int)

# Set the border elements to 1
array_2d[0, :] = 1  # Top row
array_2d[-1, :] = 1  # Bottom row
array_2d[:, 0] = 1  # Leftmost column
array_2d[:, -1] = 1  # Rightmost column

print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
import numpy as np

# Existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Size of the border to add
border_size = 1

# Determine the new shape of the array with the border
new_shape = (existing_array.shape[0] + 2 * border_size, existing_array.shape[1] + 2 * border_size)

# Create a new array filled with zeros of the new shape
new_array = np.zeros(new_shape, dtype=existing_array.dtype)

# Copy the existing array into the center of the new array
new_array[border_size:border_size+existing_array.shape[0], border_size:border_size+existing_array.shape[1]] = existing_array

print("Existing Array:")
print(existing_array)

print("\nArray with Border:")
print(new_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:


# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5), dtype=int)

# Set values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:

# Create an 8x8 matrix filled with zeros
checkerboard_matrix = np.zeros((8, 8), dtype=int)

# Set the checkerboard pattern
checkerboard_matrix[1::2, ::2] = 1  # Odd rows, even columns
checkerboard_matrix[::2, 1::2] = 1  # Even rows, odd columns

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [58]:
import numpy as np

shape = (6, 7, 8)
desired_element_index = 100

# Calculate the indices (x, y, z) from the linear index
x = desired_element_index // (shape[1] * shape[2])
remainder = desired_element_index % (shape[1] * shape[2])
y = remainder // shape[2]
z = remainder % shape[2]

print("Index (x, y, z) of the 100th element:", (x, y, z))


Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [59]:


# Define the checkerboard pattern as a 2x2 matrix
checkerboard_pattern = np.array([[0, 1], [1, 0]])

# Create the 8x8 checkerboard matrix using tile
checkerboard_matrix = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [60]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Find the minimum and maximum values in the matrix
min_value = random_matrix.min()
max_value = random_matrix.max()

# Normalize the matrix to a range of [0, 1]
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[5.65292733e-01 8.46366823e-01 3.51271960e-01 3.17625892e-01
  2.20064722e-01]
 [5.51360680e-01 2.97856796e-01 5.64595662e-01 6.63973685e-01
  3.36101922e-01]
 [5.38353518e-01 1.25870037e-01 7.39102977e-01 8.74050171e-01
  2.20022065e-01]
 [5.34813911e-01 4.83316592e-01 4.45681807e-01 2.13828180e-04
  2.55522359e-01]
 [9.78438748e-02 5.67689100e-01 8.83741428e-01 6.57804894e-01
  9.82903853e-01]]

Normalized Matrix:
[[0.57503271 0.86105789 0.35724198 0.32300324 0.22372354]
 [0.56085524 0.30288592 0.57432336 0.67545191 0.34180473]
 [0.54761896 0.12786963 0.7519046  0.88922887 0.22368013]
 [0.544017   0.49161257 0.45331485 0.         0.25980576]
 [0.09934979 0.57747129 0.89909084 0.66917446 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [2]:
import numpy as np

# Define the start and end dates for July 2016
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

# Generate all the dates corresponding to the month of July 2016
dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(dates)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
import numpy as np

# Assuming A and B are NumPy arrays of the same shape
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype= float)

# Perform the computation in place
A += B
A *= -1/2

print(A)


[-2.5 -3.5 -4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [19]:
import numpy as np

matrix = np.arange(5).reshape(-1, 1) + np.arange(5)

print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [29]:
import numpy as np

def integer_generator():
    for i in range(10):
        yield i

# Create an array using the generator function
array = np.fromiter(integer_generator(), dtype=int)

print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [30]:

# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, num=10, endpoint=False)

print(vector)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, num=12, endpoint=False)[1:-1]

print(vector)


[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
import numpy as np

# Create a small array
small_array = np.array([1, 2, 3, 4, 5])

# Perform the sum using np.sum
result_np_sum = np.sum(small_array)

# Perform the sum using built-in sum function
result_builtin_sum = sum(small_array)

print("Sum using np.sum:", result_np_sum)
print("Sum using built-in sum:", result_builtin_sum)


Sum using np.sum: 15
Sum using built-in sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [47]:
import numpy as np

# Generate two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if arrays A and B are equal
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable
my_array.flags.writeable = False

# Try to modify the array (this will raise an error)
# my_array[0] = 10  # Uncomment this line to see the error

print(my_array)


[1 2 3 4 5]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [50]:
import numpy as np

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
r = np.linalg.norm(cartesian_coordinates, axis=1)
theta = np.arctan2(cartesian_coordinates[:, 1], cartesian_coordinates[:, 0])

# Convert angles to degrees (optional)
theta_degrees = np.degrees(theta)

# Create a 10x2 matrix representing polar coordinates
polar_coordinates = np.column_stack((r, theta_degrees))

print("Cartesian Coordinates:")
print(cartesian_coordinates)

print("\nPolar Coordinates:")
print(polar_coordinates)


Cartesian Coordinates:
[[0.17604279 0.72844895]
 [0.56638821 0.52209974]
 [0.75809329 0.21236954]
 [0.48498824 0.87292616]
 [0.14732512 0.39015015]
 [0.98015808 0.89957317]
 [0.75750243 0.8654536 ]
 [0.88878461 0.29389788]
 [0.04370708 0.94062255]
 [0.47066847 0.11082137]]

Polar Coordinates:
[[ 0.74941907 76.41393777]
 [ 0.77031405 42.67003113]
 [ 0.78727775 15.64949437]
 [ 0.99860587 60.94392814]
 [ 0.41703936 69.31289476]
 [ 1.33039158 42.5452078 ]
 [ 1.15013906 48.80543212]
 [ 0.93611647 18.29770329]
 [ 0.94163745 87.3396009 ]
 [ 0.48353922 13.24926887]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:

 import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

print("Original Vector:")
print(random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("\nVector after replacing the maximum value with 0:")
print(random_vector)


Original Vector:
[0.88611917 0.2339219  0.02687925 0.3844695  0.34777795 0.08647564
 0.893642   0.54499422 0.23327765 0.48649271]

Vector after replacing the maximum value with 0:
[0.88611917 0.2339219  0.02687925 0.3844695  0.34777795 0.08647564
 0.         0.54499422 0.23327765 0.48649271]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [54]:
import numpy as np

# Number of points in each direction
n_points = 5

# Generate a grid of x and y coordinates
x = np.linspace(0, 1, n_points)
y = np.linspace(0, 1, n_points)
x_grid, y_grid = np.meshgrid(x, y)

# Create the structured array
structured_array = np.column_stack((x_grid.ravel(), y_grid.ravel()))

print(structured_array)


[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [55]:
import numpy as np

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5])

# Calculate the Cauchy matrix using broadcasting
C = 1 / (X[:, np.newaxis] - Y)

print(C)


[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [2]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

np.set_printoptions(threshold=np.inf)

print(my_array)


[ 1  2  3  4  5  6  7  8  9 10]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [5]:
a= np.array([1,2,3,4,5,6])
target= 9
b= np.abs(a-target)
c=np.argmin(b)
a[c]


6

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [6]:
import numpy as np

def sliding_window_average(arr, window_size):
    # Create a window with equal weights (for calculating the average)
    window = np.ones(window_size) / window_size

    # Use numpy.convolve to calculate the moving average
    return np.convolve(arr, window, mode='valid')


data_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Window size for the sliding window
window_size = 3

# Calculate moving averages using the sliding window
averages = sliding_window_average(data_array, window_size)

print("Original Array:", data_array)
print("Moving Averages with Window Size", window_size, ":", averages)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Moving Averages with Window Size 3 : [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [7]:


# One-dimensional array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Build the two-dimensional array
rows = len(Z) - 2
two_dimensional_array = np.vstack([Z[i:i+3] for i in range(rows)])

print(two_dimensional_array)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [8]:

my_boolean = True

# Negate the boolean inplace
my_boolean = not my_boolean

print(my_boolean)


False


In [9]:
my_float = 3.14

# Change the sign of the float inplace
my_float = -my_float

print(my_float)


-3.14


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [10]:
import numpy as np

def distance_to_lines(p, P0, P1):
    x, y = p
    x1, y1 = P0[:, 0], P0[:, 1]
    x2, y2 = P1[:, 0], P1[:, 1]

    numerator = np.abs((y2 - y1) * x - (x2 - x1) * y + (x2 * y1 - x1 * y2))
    denominator = np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

    distances = numerator / denominator
    return distances

# Example points for the lines P0 and P1
P0 = np.array([[1, 2], [3, 4], [5, 6]])
P1 = np.array([[7, 8], [9, 10], [11, 12]])

# Example point p
p = np.array([0, 0])

# Calculate the distance from p to each line
distances = distance_to_lines(p, P0, P1)

print("Distances to each line:")
print(distances)


Distances to each line:
[0.70710678 0.70710678 0.70710678]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [12]:
import numpy as np

def extract_subpart(arr, center, shape, fill_value=0):
    center = np.array(center)
    shape = np.array(shape)

    # Calculate the lower and upper bounds for each dimension
    lower_bounds = np.maximum(center - (shape - 1) // 2, 0)
    upper_bounds = np.minimum(center + shape // 2 + 1, np.array(arr.shape))

    # Calculate the slices for subpart extraction
    slices = tuple(slice(lower, upper) for lower, upper in zip(lower_bounds, upper_bounds))

    # Extract the subpart from the original array
    subpart = np.full(shape, fill_value)
    subpart_slices = tuple(slice((shape[i] - (upper - lower)) // 2, (shape[i] - (upper - lower)) // 2 + (upper - lower))
                           for i, (lower, upper) in enumerate(zip(lower_bounds, upper_bounds)))
    subpart[subpart_slices] = arr[slices]

    return subpart

# Example arbitrary array
arr = np.random.randint(0, 10, (6, 6))

# Center and shape of the subpart to extract
center = (2, 3)
shape = (3, 3)

# Extract the subpart centered on the given element with padding
subpart = extract_subpart(arr, center, shape, fill_value=-1)

print("Original Array:")
print(arr)
print("\nSubpart with Shape (3, 3) Centered on (2, 3):")
print(subpart)


Original Array:
[[2 3 7 8 2 2]
 [2 8 7 7 5 2]
 [7 1 4 5 0 5]
 [1 8 3 8 8 2]
 [0 1 9 6 1 6]
 [2 4 0 7 9 1]]

Subpart with Shape (3, 3) Centered on (2, 3):
[[7 7 5]
 [4 5 0]
 [3 8 8]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [13]:
import numpy as np

def generate_subarrays(arr, window_size):
    shape = (len(arr) - window_size + 1, window_size)
    strides = (arr.itemsize, arr.itemsize)
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

# Given array Z
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Window size for subarrays
window_size = 4

# Generate array R
R = generate_subarrays(Z, window_size)

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [14]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix:")
print(matrix)
print("Rank of the matrix:", rank)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [15]:
import numpy as np

# Example array
my_array = np.array([1, 2, 3, 2, 4, 3, 2, 5, 4, 2, 6, 7, 8, 2, 2])

# Find unique elements and their counts
unique_elements, counts = np.unique(my_array, return_counts=True)

# Find the index of the most frequent value
most_frequent_index = np.argmax(counts)

# Get the most frequent value
most_frequent_value = unique_elements[most_frequent_index]

print("Array:", my_array)
print("Most frequent value:", most_frequent_value)


Array: [1 2 3 2 4 3 2 5 4 2 6 7 8 2 2]
Most frequent value: 2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [16]:
import numpy as np

# Create a random 10x10 matrix
matrix = np.random.randint(0, 100, (10, 10))

# Function to extract all contiguous 3x3 blocks
def extract_contiguous_blocks(matrix):
    rows, cols = matrix.shape
    block_size = 3
    blocks = []

    for i in range(rows - block_size + 1):
        for j in range(cols - block_size + 1):
            block = matrix[i:i+block_size, j:j+block_size]
            blocks.append(block)

    return blocks

# Extract all contiguous 3x3 blocks from the matrix
contiguous_blocks = extract_contiguous_blocks(matrix)

# Print the extracted blocks
for i, block in enumerate(contiguous_blocks):
    print(f"Block {i+1}:")
    print(block)
    print()


Block 1:
[[89 29 86]
 [87 43 56]
 [62  6  5]]

Block 2:
[[29 86 61]
 [43 56 19]
 [ 6  5 25]]

Block 3:
[[86 61 83]
 [56 19 19]
 [ 5 25  9]]

Block 4:
[[61 83 10]
 [19 19 59]
 [25  9 28]]

Block 5:
[[83 10 65]
 [19 59 56]
 [ 9 28 45]]

Block 6:
[[10 65 51]
 [59 56 42]
 [28 45 63]]

Block 7:
[[65 51 56]
 [56 42 28]
 [45 63 71]]

Block 8:
[[51 56 14]
 [42 28  6]
 [63 71 51]]

Block 9:
[[87 43 56]
 [62  6  5]
 [88 68 69]]

Block 10:
[[43 56 19]
 [ 6  5 25]
 [68 69 19]]

Block 11:
[[56 19 19]
 [ 5 25  9]
 [69 19 32]]

Block 12:
[[19 19 59]
 [25  9 28]
 [19 32 36]]

Block 13:
[[19 59 56]
 [ 9 28 45]
 [32 36 73]]

Block 14:
[[59 56 42]
 [28 45 63]
 [36 73  2]]

Block 15:
[[56 42 28]
 [45 63 71]
 [73  2 82]]

Block 16:
[[42 28  6]
 [63 71 51]
 [ 2 82 27]]

Block 17:
[[62  6  5]
 [88 68 69]
 [ 8 16 48]]

Block 18:
[[ 6  5 25]
 [68 69 19]
 [16 48 11]]

Block 19:
[[ 5 25  9]
 [69 19 32]
 [48 11 93]]

Block 20:
[[25  9 28]
 [19 32 36]
 [11 93 27]]

Block 21:
[[ 9 28 45]
 [32 36 73]
 [93 27 72]]

B

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [17]:
import itertools

# Example vectors
vector1 = [1, 2, 3]
vector2 = ['a', 'b']
vector3 = [10, 20]

# Build the cartesian product of the vectors
cartesian_product = list(itertools.product(vector1, vector2, vector3))

print(cartesian_product)


[(1, 'a', 10), (1, 'a', 20), (1, 'b', 10), (1, 'b', 20), (2, 'a', 10), (2, 'a', 20), (2, 'b', 10), (2, 'b', 20), (3, 'a', 10), (3, 'a', 20), (3, 'b', 10), (3, 'b', 20)]


#### 91. How to create a record array from a regular array? (★★★)

In [18]:
import numpy as np

# Regular array
regular_array = np.array([(1, 'John', 25),
                          (2, 'Alice', 30),
                          (3, 'Bob', 22)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# Create a record array from the regular array
record_array = np.rec.array(regular_array)

print(record_array)



[(1, 'John', 25) (2, 'Alice', 30) (3, 'Bob', 22)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [19]:
import numpy as np

# Create a large vector Z (example with 1000 elements)
Z = np.random.rand(1000)

# Compute Z to the power of 3 using numpy.power
result1 = np.power(Z, 3)


In [20]:
import numpy as np

# Create a large vector Z (example with 1000 elements)
Z = np.random.rand(1000)

# Compute Z to the power of 3 using the ** operator
result2 = Z ** 3


In [22]:
import numpy as np

# Create a large vector Z (example with 1000 elements)
Z = np.random.rand(1000)

# Compute Z to the power of 3 using the ** operator
result2 = Z ** 3


In [21]:
import numpy as np

# Create a large vector Z (example with 1000 elements)
Z = np.random.rand(1000)

# Compute Z to the power of 3 using numpy.multiply
result3 = np.multiply(Z, Z, Z)
# Alternatively, you can use the * operator for element-wise multiplication
# result3 = Z * Z * Z


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [26]:
import numpy as np

# Create a 10x3 matrix (example)
matrix = np.array([[1, 2, 3],
                   [4, 4, 4],
                   [5, 5, 5],
                   [2, 2, 3],
                   [6, 7, 8],
                   [9, 9, 9],
                   [3, 3, 3],
                   [1, 1, 1],
                   [2, 2, 2],
                   [7, 7, 7]])

# Find rows with unequal values
rows_with_unequal_values = matrix[~np.all(matrix == matrix[0, :], axis=1)]

print(rows_with_unequal_values)


[[4 4 4]
 [5 5 5]
 [2 2 3]
 [6 7 8]
 [9 9 9]
 [3 3 3]
 [1 1 1]
 [2 2 2]
 [7 7 7]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [27]:
import numpy as np

# Example vector of integers
vector_ints = np.array([1, 2, 3, 4, 5])

# Convert the vector of integers into a matrix binary representation
matrix_binary = np.unpackbits(vector_ints[:, np.newaxis].astype(np.uint8), axis=1)

print(matrix_binary)



[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [28]:
import numpy as np

# Example two-dimensional array
two_d_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [1, 2, 3],
                        [7, 8, 9],
                        [4, 5, 6]])

# Extract unique rows from the two-dimensional array
unique_rows = np.unique(two_d_array, axis=0)

print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [29]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Equivalent to np.inner(A, B)
inner_product = np.einsum('i,i->', A, B)

print(inner_product)  # Output: 32


32


In [30]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Equivalent to np.outer(A, B)
outer_product = np.einsum('i,j->ij', A, B)

print(outer_product)



[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [31]:
import numpy as np

A = np.array([1, 2, 3, 4])

# Equivalent to np.sum(A)
sum_result = np.einsum('i->', A)

print(sum_result)  # Output: 10



10


In [32]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Equivalent to np.multiply(A, B) or A * B
mul_result = np.einsum('i,i->i', A, B)

print(mul_result)  # Output: [ 4 10 18]


[ 4 10 18]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [33]:
import numpy as np

# Example path described by two vectors (X, Y)
X = np.array([1, 2, 4, 7, 10])
Y = np.array([3, 6, 8, 9, 12])

# Number of equidistant samples
num_samples = 10

# Sample the path using equidistant samples
sampled_X = np.linspace(X[0], X[-1], num_samples)
sampled_Y = np.interp(sampled_X, X, Y)

print("Sampled X:", sampled_X)
print("Sampled Y:", sampled_Y)


Sampled X: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Sampled Y: [ 3.          6.          7.          8.          8.33333333  8.66666667
  9.         10.         11.         12.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [36]:
import numpy as np

# Example 2D array X
X = np.array([[1, 2, 3],
              [4, 2, 4],
              [0, 0, 6],
              [2, 3, 5],
              [3, 1, 2],
              [6, 2, 1]])

# Given integer n
n = 6

# Function to check if a row contains only integers and sum to n
def is_multinomial_row(row):
    return np.all(row.astype(int) == row) and np.sum(row) == n

# Use numpy.apply_along_axis to apply the function along rows
selected_rows = X[np.apply_along_axis(is_multinomial_row, 1, X)]

print(selected_rows)


[[1 2 3]
 [0 0 6]
 [3 1 2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [37]:
import numpy as np

# Example 1D array X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap samples
N = 1000

# Array to store the sample means
sample_means = np.zeros(N)

# Perform bootstrapping
for i in range(N):
    # Resample with replacement
    resampled_X = np.random.choice(X, size=len(X), replace=True)
    # Compute the mean of the resampled sample
    sample_means[i] = np.mean(resampled_X)

# Calculate the 95% confidence interval
confidence_interval = np.percentile(sample_means, [2.5, 97.5])

print("95% Confidence Interval:", confidence_interval)


95% Confidence Interval: [3.7975 7.2   ]
